package in.lakshay.rentACarBackend.business.requests.brandRequests;

// validation annotations
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

// lombok stuff - saves typing
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// request obj for creating new car brands
// used in POST /api/brands/add endpoint
@Data // lombok magic - getters, setters, etc
@AllArgsConstructor // ctor with all args
@NoArgsConstructor // default ctor
public class CreateBrandRequest {

	// validation - name cant be null or empty and must be between 3-30 chars
	// these annotations are processed by spring validation
	@NotNull // can't be null
	@NotBlank // can't be empty or just whitespace
	@Size(min = 3, max = 30)  // dont want crazy long names - reasonable limits
	private String brandName; // like "Toyota", "Honda", etc

	// pretty simple request - just need the name
	// id is generated by the db
}
